DROP TABLE IF EXISTS `RATE_LIMIT_CONFIG`;
DROP TABLE IF EXISTS `DEVELOPERS`;
DROP TABLE IF EXISTS `ORGANIZATIONS`;

CREATE TABLE RATE_LIMIT_CONFIG (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_id VARCHAR(250) NOT NULL,
  api_uri VARCHAR(250) NOT NULL,
  rate_limit INT NOT NULL,
  reset_interval INT NOT NULL
);
CREATE TABLE DEVELOPERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  position VARCHAR(250) NOT NULL,
  project_assigned VARCHAR(250) NOT NULL,
  primary_skill VARCHAR(250) NOT NULL
);
CREATE TABLE ORGANIZATIONS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  domain VARCHAR(250) NOT NULL,
  head_count VARCHAR(250) NOT NULL,
  head_quater VARCHAR(250) NOT NULL
);




